# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='hits',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
